/**
 * TLS-Scanner - A TLS configuration and analysis tool based on TLS-Attacker.
 *
 * Copyright 2017-2019 Ruhr University Bochum / Hackmanit GmbH
 *
 * Licensed under Apache License 2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 */
package de.rub.nds.tlsscanner.report;

public enum AnalyzedProperty {
    SUPPORTS_SSL_2,
    SUPPORTS_SSL_3,
    SUPPORTS_TLS_1_0,
    SUPPORTS_TLS_1_1,
    SUPPORTS_TLS_1_2,
    SUPPORTS_TLS_1_3,
    SUPPORTS_TLS_1_3_DRAFT,
    SUPPORTS_DTLS_1_0,
    SUPPORTS_DTLS_1_2,
    SUPPORTS_DTLS_1_3,
    SUPPORTS_PFS,
    SUPPORTS_NULL_CIPHERS,
    SUPPORTS_FORTEZZA,
    SUPPORTS_EXPORT,
    SUPPORTS_ANON,
    SUPPORTS_DES,
    SUPPORTS_3DES,
    SUPPORTS_SEED,
    SUPPORTS_IDEA,
    SUPPORTS_RC2,
    SUPPORTS_RC4,
    SUPPORTS_CBC,
    SUPPORTS_AEAD,
    SUPPORTS_EXTENDED_MASTER_SECRET,
    SUPPORTS_ENCRYPT_THEN_MAC,
    SUPPORTS_MONTOGMERY_CURVES,
    SUPPORTS_SESSION_TICKETS,
    SUPPORTS_SESSION_IDS,
    SUPPORTS_SECURE_RENEGOTIATION_EXTENSION,
    SUPPORTS_TOKENBINDING,
    SUPPORTS_TLS_COMPRESSION,
    SUPPORTS_COMMON_DH_PRIMES,
    SUPPORTS_PRIME_MODULI,
    SUPPORTS_SAFEPRIME_MODULI,
    SUPPORTS_INSECURE_RENEGOTIATION,
    SUPPORTS_RENEGOTIATION,
    SUPPORTS_HSTS,
    SUPPORTS_HPKP_REPORTING,
    SUPPORTS_HTTP_COMPRESSION,
    
    PREFERS_PFS,
    ENFORCES_PFS,
    ENFOCRES_CS_ORDERING,
    
    HAS_VERSION_INTOLERANCE,
    HAS_CIPHERSUITE_INTOLERANCE,
    HAS_EXTENSION_INTOLERANCE,
    HAS_CIPHERSUITE_LENGTH_INTOLERANCE,
    HAS_COMPRESSION_INTOLERANCE,
    HAS_ALPN_INTOLERANCE,
    HAS_CLIENTHELLO_LENGTH_INTOLERANCE,
    HAS_EMPTY_LAST_EXTENSION_INTOLERANCE,
    HAS_SIG_HASH_ALGORITHM_INTOLERANCE,
    HAS_BIG_CLIENT_HELLO_INTOLERANCE,
    HAS_NAMED_GROUP_INTOLERANCE,
    
    HAS_SECOND_CIPHERSUITE_BYTE_BUG,
    REFLECTS_OFFERED_CIPHERSUITES,
    IGNORES_OFFERED_CIPHERSUITES,
    IGNORES_OFFERED_NAMED_GROUPS,
    IGNORES_OFFERED_SIG_HASH_ALGOS,
    
    VULNERABLE_TO_BLEICHENBACHER,
    VULNERABLE_TO_CBC_PADDING_ORACLE,
    VULNERABLE_TO_INVALID_CURVE,
    VULNERABLE_TO_INVALID_CURVE_EPHEMERAL,
    VULNERABLE_TO_INVALID_CURVE_EPHEMERAL_WITH_REUSE,
    VULNERABLE_TO_POODLE,
    VULNERABLE_TO_TLS_POODLE,
    VULNERABLE_TO_SWEET_32,
    VULNERABLE_TO_DROWN,
    VULNERABLE_TO_HEARTBLEED,
    VULNERABLE_TO_TICKETBLEED,
    VULNERABLE_TO_EARLY_CCS,
    
    MISSES_MAC_APPDATA_CHECKS,
    MISSES_CHECKS_MAC_FINISHED_CHECKS,
    MISSES_CHECKS_VERIFY_DATA_CHECKS,
    
    HAS_CERTIFICATE_ISSUES,
    
    HAS_WEAK_RANDOMNESS,
    
    REUSES_EC_PUBLICKEY,
    REUSES_DH_PUBLICKEY,
    REUSES_GCM_NONCES
}
